import {
  BillingInterval,
  SubscriptionPlan,
  AiMatcherTier,
  AnalyticsTier,
  SupportTier,
  AddonType,
} from '../common/enums/enums';

export const PLAN_LIMITS = {
  [SubscriptionPlan.FREE]: {
    jobPostsPerMonth: 1,
    applicantsPerJob: 25,
    maxApplicantsViewable: 10,
    teamSeats: 1,
    featuredSlotsPerMonth: 0,
    aiMatcher: AiMatcherTier.NONE,
    aiInsights: false,
    hasTalentDb: false,
    hasInterviewScheduling: true,
    maxInterviewsPerMonth: 5,
    hasInterviewAutomation: false,
    hasInterviewReminders: false,
    hasCalendarSync: false,
    hasCustomEmailTemplates: false,
    hasContractTemplates: false,
    hasAdvancedContractTemplates: false,
    hasOfferLetters: false,
    hasPanelInterviews: false,
    hasAutomation: false,
    analytics: AnalyticsTier.NONE,
    hasExport: false,
    hasVerifiedBadge: false,
    hasSavedSearches: false,
    hasMarketIntel: false,
    showHiringFlyBranding: true,
    support: SupportTier.EMAIL,
  },
  [SubscriptionPlan.STARTER]: {
    jobPostsPerMonth: 3,
    applicantsPerJob: 50,
    maxApplicantsViewable: 50,
    teamSeats: 2,
    featuredSlotsPerMonth: 0,
    aiMatcher: AiMatcherTier.BASIC,
    aiInsights: false,
    hasTalentDb: false,
    hasInterviewScheduling: true,
    maxInterviewsPerMonth: 20,
    hasInterviewAutomation: false,
    hasInterviewReminders: true,
    hasCalendarSync: false,
    hasCustomEmailTemplates: false,
    hasContractTemplates: true,
    hasAdvancedContractTemplates: false,
    hasOfferLetters: true,
    hasPanelInterviews: false,
    hasAutomation: false,
    analytics: AnalyticsTier.BASIC,
    hasExport: true,
    hasVerifiedBadge: false,
    hasSavedSearches: false,
    hasMarketIntel: false,
    showHiringFlyBranding: true,
    support: SupportTier.PRIORITY,
  },
  [SubscriptionPlan.GROWTH]: {
    jobPostsPerMonth: 10,
    applicantsPerJob: 150,
    maxApplicantsViewable: Infinity,
    teamSeats: 5,
    featuredSlotsPerMonth: 1,
    aiMatcher: AiMatcherTier.BASIC,
    aiInsights: true,
    hasTalentDb: true,
    hasInterviewScheduling: true,
    maxInterviewsPerMonth: Infinity,
    hasInterviewAutomation: true,
    hasInterviewReminders: true,
    hasCalendarSync: true,
    hasCustomEmailTemplates: true,
    hasContractTemplates: true,
    hasAdvancedContractTemplates: false,
    hasOfferLetters: true,
    hasPanelInterviews: false,
    hasAutomation: true,
    analytics: AnalyticsTier.ADVANCED,
    hasExport: true,
    hasVerifiedBadge: true,
    hasSavedSearches: true,
    hasMarketIntel: false,
    showHiringFlyBranding: false,
    support: SupportTier.PRIORITY,
  },
  [SubscriptionPlan.SCALE]: {
    jobPostsPerMonth: 30,
    applicantsPerJob: Infinity,
    maxApplicantsViewable: Infinity,
    teamSeats: 10,
    featuredSlotsPerMonth: 3,
    aiMatcher: AiMatcherTier.ADVANCED,
    aiInsights: true,
    hasTalentDb: true,
    hasInterviewScheduling: true,
    maxInterviewsPerMonth: Infinity,
    hasInterviewAutomation: true,
    hasInterviewReminders: true,
    hasCalendarSync: true,
    hasCustomEmailTemplates: true,
    hasContractTemplates: true,
    hasAdvancedContractTemplates: true,
    hasOfferLetters: true,
    hasPanelInterviews: true,
    hasAutomation: true,
    analytics: AnalyticsTier.ENTERPRISE,
    hasExport: true,
    hasVerifiedBadge: true,
    hasSavedSearches: true,
    hasMarketIntel: true,
    showHiringFlyBranding: false,
    support: SupportTier.DEDICATED,
  },
} as const;

export type PlanLimits = (typeof PLAN_LIMITS)[SubscriptionPlan];

export const PLAN_PRICES: Record<SubscriptionPlan, number> = {
  [SubscriptionPlan.FREE]: 0,
  [SubscriptionPlan.STARTER]: 9999,
  [SubscriptionPlan.GROWTH]: 19999,
  [SubscriptionPlan.SCALE]: 29999,
};

export const TRIAL_DAYS = 7;

export function getPlanPrice(
  plan: SubscriptionPlan,
  interval: BillingInterval = BillingInterval.MONTHLY,
): number {
  const monthly = PLAN_PRICES[plan];
  if (interval === BillingInterval.YEARLY) return monthly * 10;
  return monthly;
}

export const ADDON_PRICES: Record<AddonType, number> = {
  [AddonType.EXTRA_POST]: 999,
  [AddonType.BOOST_CAP]: 1499,
  [AddonType.FEATURE_JOB]: 1999,
};

export const VERIFICATION_MONTHLY_PRICE = 3999;
